---
name: 'Release'

on:
  push:
    tags:
      - v*

defaults:
  run:
    shell: bash

jobs:
  build:
    name: 'Build application'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Get go version'
        id: goversion
        run: |
          set -eo pipefail
          version="$(< .go-version)"
          echo "::set-output name=version::$version"
      - name: 'Setup go'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.goversion.outputs.version }}

      - name: 'Run GoReleaser'
        uses: goreleaser/goreleaser-action@v2
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}

      - name: 'Upload artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: ssm2env
          path: dist/*

  integration:
    name: 'Run integration tests'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Install dependencies'
        run: brew install bats-core jq

      - name: 'Download artifacts'
        uses: actions/download-artifact@v2
        with:
          name: ssm2env
          path: dist/

      - name: 'Run integration tests'
        env:
          TEST_SSM2ENV_PREFIX: ${{ secrets.TF_VAR_PREFIX }}
          TEST_SSM2ENV_PARAMETERS: ${{ secrets.TF_VAR_PARAMETERS }}
          TEST_SSM2ENV_EXECUTABLE: dist/ssm2env_linux_amd64/ssm2env
          TEST_SSM2ENV_INTEGRATION: 0
        run: bats -r 'bats/*.bats'

      - name: 'Upload the release assets'
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.tar.gz
            dist/checksums.txt
