---
name: 'Validate pull request'

on: [workflow_dispatch, pull_request]

defaults:
  run:
    shell: bash

jobs:
  tests:
    name: 'Run tests'
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'go-template'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Get go version'
        id: goversion
        run: |
          set -eo pipefail
          version="$(< .go-version)"
          echo "::set-output name=version::$version"
      - name: 'Setup go'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.goversion.outputs.version }}

      - name: 'Install dependencies'
        run: go mod download

      - name: 'Run tests'
        run: go test -v ./...

  precommit:
    name: 'Run precommit check'
    runs-on: ubuntu-latest
    if: github.event.repository.name != 'go-template'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup python'
        uses: actions/setup-python@v2

      - name: 'Get go version'
        id: goversion
        run: |
          set -eo pipefail
          version="$(< .go-version)"
          echo "::set-output name=version::$version"
      - name: 'Setup go'
        uses: actions/setup-go@v2
        with:
          go-version: ${{ steps.goversion.outputs.version }}

      - name: 'Run pre-commit check'
        uses: pre-commit/action@v2.0.0
